name: Build, Lint and Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: production
    env:
      VITE_WALLET_CONNECT_PROJECT_ID: ${{ vars.VITE_WALLET_CONNECT_PROJECT_ID }}
      VITE_PARTICLE_PROJECT_ID: ${{ vars.VITE_PARTICLE_PROJECT_ID }}
      VITE_PARTICLE_CLIENT_KEY: ${{ vars.VITE_PARTICLE_CLIENT_KEY }}
      VITE_PARTICLE_APP_ID: ${{ vars.VITE_PARTICLE_APP_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Ensures you checkout the source branch that triggered the PR
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Authenticate to npm for private packages
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
