name: Release App

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Version increment (defaults to minor)
        default: minor
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch

jobs:
  release-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RELEASE_DEPLOY_KEY }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Authenticate to npm for private packages
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Setup git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release app
        run: pnpm release --increment ${{ inputs.increment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
